# Site settings
# Any custom variable will be accessible in the templates via {{ site.myvariable }}.
title: Fraser Crossman
email: fraser.crossman@domain.com
description: > # this means to ignore newlines until "baseurl:"
   This is my personal website where I share things I find interesting.
url: "http://www.frasercrossman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: frasercrossman
github_username:  frasercrossman

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass/
